Update xmlresolver 5.2.0-5.2.2 to fix pom linting for other deps (#228)
More details with the reason for this PR can be found in the build mentioned below.

```sh
Error:  Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.xmlresolver:xmlresolver:5.2.0 paths to dependency are:
+-gov.nist.secauto.oscal.tools.oscal-cli:cli-core:1.0.3-SNAPSHOT
  +-org.xmlresolver:xmlresolver:5.2.0
and
+-gov.nist.secauto.oscal.tools.oscal-cli:cli-core:1.0.3-SNAPSHOT
  +-org.xmlresolver:xmlresolver:5.2.0:data
and
+-gov.nist.secauto.oscal.tools.oscal-cli:cli-core:1.0.3-SNAPSHOT
  +-gov.nist.secauto.metaschema:metaschema-schema-generator:0.12.2
    +-org.xmlresolver:xmlresolver:5.2.0
and
+-gov.nist.secauto.oscal.tools.oscal-cli:cli-core:1.0.3-SNAPSHOT
  +-gov.nist.secauto.metaschema:metaschema-schema-generator:0.12.2
    +-org.xmlresolver:xmlresolver:5.2.0:data
and
+-gov.nist.secauto.oscal.tools.oscal-cli:cli-core:1.0.3-SNAPSHOT
  +-net.sf.saxon:Saxon-HE:12.4
    +-org.xmlresolver:xmlresolver:5.2.2
]
```

https://github.com/usnistgov/oscal-cli/actions/runs/7043933418/job/19170620781?pr=225